<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ETHTPS.Ingestion-094099c5-a432-4f88-b8e7-2bd794f8e4cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="*" />
    <PackageReference Include="Npgsql" Version="*" />
    <PackageReference Include="StackExchange.Redis" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="RPCOverrides.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
